arangodb:
    restart: always
    container_name: 'arangodb'
    image: 'arangodb:latest'
    ports:
      - '8529:8529'
    environment:
      ARANGO_ROOT_PASSWORD: 'admin'
      ARANGO_STORAGE_ENGINE: 'rocksdb'
    volumes:
      - arangodb_data:/var/lib/arangodb3
volumes:
  arangodb_data: 